-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 17:23:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `birth` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_has_Movie` (
  `Actor_id` INT NOT NULL,
  `Movie_id` INT NOT NULL,
  PRIMARY KEY (`Actor_id`, `Movie_id`),
  INDEX `fk_Actor_has_Movie_Movie1_idx` (`Movie_id` ASC) VISIBLE,
  INDEX `fk_Actor_has_Movie_Actor1_idx` (`Actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Movie_Actor1`
    FOREIGN KEY (`Actor_id`)
    REFERENCES `mydb`.`Actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Movie_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `Customer_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `Customer_number_UNIQUE` (`Customer_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_Video_tape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_has_Video_tape` (
  `Customer_id` INT NOT NULL,
  `Video_tape_id` INT NOT NULL,
  `rent_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `return_time` DATETIME NULL,
  PRIMARY KEY (`Customer_id`, `Video_tape_id`),
  INDEX `FK_VIDEO` (`Video_tape_id` ASC) INVISIBLE,
  INDEX `FK_CUSTOMER` (`Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Video_tape_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Video_tape_Video_tape1`
    FOREIGN KEY (`Video_tape_id`)
    REFERENCES `mydb`.`Video_tape` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `movie_theme` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video_tape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video_tape` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `video_type` ENUM('Beta', 'VHS') NULL,
  `Movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Video_Movie1_idx` (`Movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Video_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
